<a href="https://colab.research.google.com/github/muskan-cloud/Pytorch_deeplearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importation

In [ ]:
print("hello,starting pytorch for deep learning!")

hello,starting pytorch for deep learning!


In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



# Introduction to tensors
 creating tensors


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([6,7])
vector

tensor([6, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 11, 12]])

In [ ]:
TENSOR[0,1,2]

tensor(9)



# **RANDOM TENSORS**
WHY RANDOM TENSORS?


In [ ]:
#CREATE A RANDOM TENSOR OF SIZE(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7709, 0.3939, 0.0958, 0.9631],
        [0.4781, 0.6595, 0.1013, 0.8855],
        [0.7520, 0.9398, 0.4964, 0.3085]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor_2 = torch.rand(3,4,2)
random_tensor_2

tensor([[[0.3103, 0.6691],
         [0.2571, 0.4226],
         [0.4575, 0.0561],
         [0.0078, 0.7073]],

        [[0.3668, 0.7087],
         [0.7841, 0.0657],
         [0.2209, 0.4455],
         [0.9521, 0.9776]],

        [[0.2391, 0.8240],
         [0.7806, 0.5223],
         [0.1257, 0.3920],
         [0.7030, 0.1076]]])

In [ ]:
random_tensor_2.ndim

3

In [ ]:
random_tensor_2[1,1,1]

tensor(0.0657)

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height,width,channel
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#zeroes and ones

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# creating a range of tensors and tensors-like

In [ ]:
#Use torch.arange()
one_to_ten=torch.arange(start=0,end=11,step=2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
#creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten) #creates as same shape
ten_zeroes

tensor([0, 0, 0, 0, 0, 0])

# TENSOR DATATYPES

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,#datatype of tensor
                                device=None, #(for_eg=cpu,gpu,cuda)
                                requires_grad = False)#whether or not to track gradients
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

# Getting information from tensors
1.`tensor.dtype` to get datatype of tensor
2. `tensor.shape` to get shape of tensor
3.`tensor.device` to get device of tensor

# Tensor Operations

In [ ]:
tensor = torch.tensor([10,20,45])
add_tensor = tensor + 67
add_tensor

tensor([ 77,  87, 112])

In [ ]:
sub_tensor = tensor - 9
sub_tensor

tensor([ 1, 11, 36])

In [ ]:
mul_tensor = tensor * 6
mul_tensor

tensor([ 60, 120, 270])

In [ ]:
div_tensor = tensor / 2
div_tensor

tensor([ 5.0000, 10.0000, 22.5000])

In [ ]:
#builtinfunctions
torch.mul(tensor,6)

tensor([ 60, 120, 270])

In [ ]:
torch.add(tensor,6)

tensor([16, 26, 51])

In [ ]:
torch.sub(tensor,6)

tensor([ 4, 14, 39])

In [ ]:
torch.div(tensor,3)

tensor([ 3.3333,  6.6667, 15.0000])

In [ ]:
# Elementwise_multiplication
print(f"tensor_el_mul: {tensor*tensor}")

tensor_el_mul: tensor([ 100,  400, 2025])


In [ ]:
# Matrix_Multiplication (dot_product)
%%time
print(f"tensor_mat_mul: {torch.matmul(tensor,tensor)}")

tensor_mat_mul: 2525
CPU times: user 852 µs, sys: 792 µs, total: 1.64 ms
Wall time: 1.61 ms


In [ ]:
tensor_A=torch.rand(3,6)
tensor_B=torch.rand(3,2)
tensor_AB=torch.matmul(tensor_A.T,tensor_B)#transposed_tensor_A
tensor_AB

tensor([[0.2555, 0.4452],
        [0.6716, 1.1396],
        [0.3343, 0.4303],
        [0.3443, 0.6304],
        [0.3518, 1.0602],
        [0.3402, 1.0947]])

# Tensor_Aggregation(min,max,sum,etc..)

In [ ]:
tensor_x = torch.arange(0,51,5)
torch.min(tensor_x),tensor_x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(tensor_x),tensor_x.max()

(tensor(50), tensor(50))

In [ ]:
torch.mean(tensor_x.type(torch.float32))

tensor(25.)

In [ ]:
torch.sum(tensor_x),tensor_x.sum()

(tensor(275), tensor(275))

In [ ]:
tensor_x.argmin()#returns the position of the minimum value

tensor(0)

In [ ]:
(tensor_x.argmax(),tensor_x[tensor_x.argmax()])

(tensor(10), tensor(50))

###reshaping,stacking,squeezing, and unsqueezing tensors & permute



In [ ]:
a = torch.arange(1.,10.)
a,a.shape,a.ndim


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
#adding an extra dimension
a_reshaped = a.reshape(9,1)
a_reshaped,a_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# change the view
z= a.view(1,9)
z,z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# (changing z changes a because a view of tensor shares the same menory as the original tensor!)
z[:,0] = 5
z,a

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on top of each other
a_vstacked = torch.vstack([a,a,a,a])
a_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
a_hstacked = torch.hstack([a,a,a,a])
a_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a_stack_0 = torch.stack([a,a,a,a],dim=0)
a_stack_0

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
a_stack_1 = torch.stack([a,a,a,a],dim=1)
a_stack_1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze()
a_reshaped.shape

torch.Size([9, 1])

In [ ]:
a_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
a_4 = a.reshape(1,3,3,1)
a_4

tensor([[[[5.],
          [2.],
          [3.]],

         [[4.],
          [5.],
          [6.]],

         [[7.],
          [8.],
          [9.]]]])

In [ ]:
a_4_s = a_4.squeeze()
a_4_s,a_4_s.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
a_4_us = a_4_s.unsqueeze(dim=(0))
a_4_us_2= a_4_us.unsqueeze(dim=3)
a_4_us.shape,a_4_us_2.shape

(torch.Size([1, 3, 3]), torch.Size([1, 3, 3, 1]))

In [ ]:
# torch.permute()
c_original = torch.rand(size=(224,224,3)) #[height,width,color_channels]
#Permute the original tensor to rearrange the axis (or dim) order
c_permuted = c_original.permute(2,0,1)
c_original.shape,c_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
c_permuted[0,0,0]

tensor(0.2511)

In [ ]:
c_original[0,0,0] = 1
# (changing c_og changes c_perm because permuted works as view with dimensions swapped of tensor shares the same menory as the original tensor!)
c_permuted[0,0,0]

tensor(1.)

# Indexing (selecting data from tensors)
Indexing with pytorch is similar to indexing with numpy

In [ ]:
d = torch.arange(1,10).reshape(1,3,3)
d , d.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
d[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
d[0,1],d[0][1]

(tensor([4, 5, 6]), tensor([4, 5, 6]))

In [ ]:
d[0,1,1],d[0][1][0]

(tensor(5), tensor(4))

In [ ]:
# getting all values of zeoth and 1st dim but only 1 of 2nd dim
d[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
d_sq = d.unsqueeze(dim=3)
d_sq


tensor([[[[1],
          [2],
          [3]],

         [[4],
          [5],
          [6]],

         [[7],
          [8],
          [9]]]])

In [ ]:
d_sq[:,:,0,0]

tensor([[1, 4, 7]])

In [ ]:
d[:,1,1]

tensor([5])

In [ ]:
# q: get index 0 of 0th and 1st dim and all values of 2nd dim
d[0,0,:]

tensor([1, 2, 3])

In [ ]:
#ques:index on d to return 9
#ques index on d to return 3,6,9
d[0,2,2],d[0,:,2]

(tensor(9), tensor([3, 6, 9]))

# Pytorch tensors and numpy
Numpy is a popular scientific python numerical computing library
& 'coz of this pytorch has functionality to interact with it.


*  Data in numpy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
*  Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`




In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the value of array what will this do to tensor?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the value of tensor what will this do to array?
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#REPRODUCIBILITY (Trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data  again and again...`

To reduce the randomness in neural networks and pytorch comes the concept of ** randomseed ** . essentially what the random seed does is "flavour" the randomness.

In [ ]:
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(3,4)
print(tensor_a)
print(tensor_b)

print(tensor_a == tensor_b)

tensor([[0.0972, 0.3158, 0.0062, 0.2253],
        [0.3250, 0.2880, 0.1860, 0.7928],
        [0.3560, 0.4681, 0.4795, 0.0198]])
tensor([[0.5350, 0.9795, 0.5002, 0.6230],
        [0.3148, 0.7392, 0.0043, 0.2965],
        [0.9389, 0.6441, 0.2677, 0.3633]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
random_seed = 42
torch.manual_seed(random_seed)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and Pytorch objects on GPUs (for faster computation)


### 1. Getting a GPU

You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

| **Method** | **Difficulty to setup** | **Pros** | **Cons** | **How to setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time to setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |

There are more options for using GPUs but the above three will suffice for now.

Personally, I use a combination of Google Colab and my own personal computer for small scale experiments (and creating this course) and go to cloud resources when I need more compute power.

> **Resource:** If you're looking to purchase a GPU of your own but not sure what to get, [Tim Dettmers has an excellent guide](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".



In [ ]:
!nvidia-smi

Thu Jan  4 13:22:25 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

###2. CHECK FOR GPU ACCESS WITH PYTORCH

In [ ]:
import torch
torch.cuda.is_available()


True

In [ ]:
# setup device agnostic code

device = "cuda"  if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and Models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# 4.Moving Tensors back to the CPU

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
x=torch.rand(7,7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
y=torch.rand(1,7)
# Perform matrix multiplication
x@y.T

tensor([[2.4389],
        [2.1219],
        [2.8024],
        [2.6756],
        [1.2561],
        [2.3681],
        [2.1310]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)
# Create two random tensors
x=torch.rand(7,7)
torch.manual_seed(random_seed)
y=torch.rand(1,7)
# Matrix multiply tensors
x@y.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
seed = 1234
random_seed = torch.cuda.manual_seed(seed)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed

random_seed = torch.manual_seed(1234)
tensor_A = torch.rand(2,3)
random_seed = torch.manual_seed(1234)
tensor_B = torch.rand(2,3)

# Check for access to GPU
device = "cuda"  if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tensor_A_gpu=tensor_A.to(device)
tensor_B_gpu=tensor_B.to(device)
tensor_A_gpu,tensor_B_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
mat_mulAB=torch.matmul(tensor_A_gpu,tensor_B_gpu.T)
mat_mulAB

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f'max =',torch.max(mat_mulAB))
# Find min
print(f'min =',torch.min(mat_mulAB))

max = tensor(0.6287, device='cuda:0')
min = tensor(0.2161, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f'index of max =',torch.argmax(mat_mulAB))

# Find arg min
print(f'index of min =',torch.argmin(mat_mulAB))

index of max = tensor(3, device='cuda:0')
index of min = tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
import torch
# Set seed
random_seed = 7
torch.manual_seed(random_seed)

# Create random tensor
x = torch.rand(1,1,1,10)

# Remove single dimensions
x_squeezed=x.squeeze()

# Print out tensors and their shapes
print(f'normal tensor:',x,'shape:',x.shape)
print(f'squeezed tensor:',x_squeezed,'shape:',x_squeezed.shape)

normal tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) shape: torch.Size([1, 1, 1, 10])
squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) shape: torch.Size([10])
